export default [
  {
    name: "room_id",
    title: '<i class="white user outline icon"></i>房屋id',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
    sortField: "usage1"
  },
  {
    name: "cert_id",
    title: '<i class="white address card icon"></i>权证号',
    width: "10%",
    sortField: "cert_id",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "owner",
    sortField: "owner",
    title: '<i class="white sitemap icon"></i>权证人',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "address",
    sortField: "group_id",
    title: '<i class="white sitemap icon"></i>房屋地址',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "roomname",
    sortField: "roomname",
    title: '<i class="white sitemap icon"></i>房屋名称',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "usage",
    sortField: "usage",
    title: '<i class="white sitemap icon"></i>房屋用途',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "space",
    sortField: "space",
    title: '<i class="white sitemap icon"></i>面积',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "age",
    sortField: "age",
    title: '<i class="white sitemap icon"></i>建造年代',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "action",
    title: '<i class="white heterosexual icon"></i>操作',
    titleClass: "center aligned",
    dataClass: "center aligned",
    width: "10%",
  },
];
