export default [
  {
    name: "room_id",
    title: '房屋id',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "cert_id",
    title: '权证号',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "owner",
    title: '权证人',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "address",
    title: '房屋地址',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "roomname",
    title: '房屋名称',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "usage",
    title: '房屋用途',
    width: "10%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "space",
    title: '面积',
    width: "5%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "age",
    title: '建造年代',
    width: "5%",
    titleClass: 'center aligned',
    dataClass: 'center aligned',
  },
  {
    name: "action",
    title: '操作',
    titleClass: "center aligned",
    dataClass: "center aligned",
    width: "30%",
  },
];
