const constantsJinhui = {
    typeSuccess:"success",
    typeError:"error",
    NEW:"新建",
    PASS:"通过",
    FAIL:"拒绝",
    WEIXIU:"维修",
    CREATESUCCESS:"创建成功",
    GENERALERROR:"错误",
    DELETESUCCEFAILEDSS:"删除成功",
    EDITSUCCESS:"编辑成功",
    EDITFAILED:"编辑失败",
    DELETEFAILED:"删除失败",
    DELETESUCCESS:"删除成功",
    CREATEFAILED:"创建失败",
    FENPEISUCCESS:"分配成功",
    FENPEIFAILED:"分配失败",
    FEIPEICREATEFAILED:"分配单位失败错误代码：",
    STATUSNEW:1,
    typeRoomPatrol:'Patrol',
    typeRoomAssignment:2,
    typeRentRoom:2,
    typeRoom:1,
    fileURL:"http://118.190.204.202:9003/getoss?key="
}
export default constantsJinhui;