export default [
  {
    name: "rentowner",
    title: '出租人',
    width: "20%",
    height:"100px",
    sortField: "rentowner",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "rentunit",
    title: '出租单位',
    width: "20%",
    sortField: "cert_id",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "rent_mobile",
    sortField: "enumber",
    title: '手机号',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "starttime",
    sortField: "level",
    title: '开始时间',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "endtime",
    sortField: "level",
    title: '结束时间',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "action",
    title: '操作',
    titleClass: "center aligned",
    dataClass: "center aligned",
    width: "15%"
  },
];
