export default [
  {
    name: "name",
    title: '单位名称',
    width: "20%",
    height:"100px",
    sortField: "name",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "level_num",
    title: '各个级别人数',
    width: "20%",
    sortField: "cert_id",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "enumber",
    sortField: "enumber",
    title: '单位人数',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "level",
    sortField: "level",
    title: '单位级别',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "zhengting",
    sortField: "zhengting",
    title: '正厅',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "futing",
    sortField: "futing",
    title: '副厅',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "zhengchu",
    sortField: "zhengchu",
    title: '正处',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "fuchu",
    sortField: "fuchu",
    title: '副处',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "zhengke",
    sortField: "zhengke",
    title: '正科',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "fuke",
    sortField: "fuke",
    title: '副科',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "keji",
    sortField: "keji",
    title: '科级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "action",
    title: '操作',
    titleClass: "center aligned",
    dataClass: "",
    width: "70px"
  },
];
