export default [
  {
    name: "roomname",
    title: '房屋名称',
    width: "20%",
    sortField: "roomname",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "buildingname",
    sortField: "building_name",
    title: '楼名',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "floorname",
    sortField: "floorname",
    title: '楼层',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "roomnumber",
    sortField: "roomnumber",
    title: '房间号',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
    {
    name: "room_type",
    sortField: "room_type",
    title: '房屋类型',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "keji",
    title: '科级',
    width: "20%",
    height:"100px",
    sortField: "leader",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "fukeji",
    title: '副科级',
    width: "20%",
    sortField: "roomname",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "keyuan",
    title: '科员',
    width: "20%",
    sortField: "roomname",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "qita",
    title: '其他',
    width: "20%",
    sortField: "roomname",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "space",
    sortField: "space",
    title: '面积(m²)',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  }
];
