export default [
  {
    name: "out_room_name",
    title: '房屋名称',
    width: "20%",
    sortField: "out_room_name",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "building_name",
    sortField: "building_name",
    title: '楼名',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "floor_name",
    sortField: "floor_name",
    title: '楼层',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "roomnumber",
    sortField: "roomnumber",
    title: '房间号',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
    {
    name: "room_type",
    sortField: "room_type",
    title: '房屋类型',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "leader",
    title: '领导级别',
    width: "20%",
    height:"100px",
    sortField: "leader",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "roomname",
    title: '办公室名称',
    width: "20%",
    sortField: "roomname",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "space",
    sortField: "space",
    title: '面积(m²)',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  }
];
