export default [
  {
    name: "roomename",
    title: '房屋名称',
    width: "30%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "buildingname",
    title: '楼名',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "floorname",
    title: '楼层',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "roomnumber",
    title: '房间号',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "roomname",
    title: '房间名',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
    {
    name: "type",
    title: '类型',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "juji",
    title: '局级',
    width: "40px",
    height:"100px",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "fujuji",
    title: '副局级',
    width: "40px",
    height:"100px",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "chuji",
    title: '处级',
    width: "40px",
    height:"100px",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "fuchuji",
    title: '副处级',
    width: "40px",
    height:"100px",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "keji",
    title: '科级',
    width: "40px",
    height:"100px",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "fukeji",
    title: '副科级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "keyuan",
    title: '科员',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "qita",
    title: '其他',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  
  {
    name: "space",
    title: '面积(m²)',
    width: "15%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "action",
    title: '操作',
    width: "150px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  }
];
