export default [
  {
    name: "name",
    title: '单位名称',
    width: "10%",
    height:"100px",
    titleClass: "center aligned",
    dataClass: "aligned",
  },
  {
    name: "roomNumber",
    title: '房间号',
    width: "10%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "roomName",
    title: '房间名',
    width: "10%",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "juji",
    title: '局级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "fujuji",
    title: '副局级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "chuji",
    title: '处级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "fuchuji",
    title: '副处级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "keji",
    title: '科级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "fukeji",
    title: '副科级',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "keyuan",
    title: '科员',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "qita",
    title: '其他',
    width: "40px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  },
  {
    name: "space",
    title: '面积(m²)',
    width: "60px",
    titleClass: "center aligned",
    dataClass: "center aligned",
  }
];
